; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = boards

; change to T5-ePaper if you have ESP32-WROVER based device (or use 'pio run -e T5-ePaper')
default_envs = T5-ePaper-S3

; src_dir = examples/button
; src_dir = examples/demo
; src_dir = examples/drawExample
; src_dir = examples/drawImages
; src_dir = examples/grayscale_test
; src_dir = examples/screen_repair
; src_dir = examples/spi_driver
; src_dir = examples/touch
; src_dir = examples/wifi_sync
; src_dir = examples/sleep
src_dir = examples/demo

[env]
lib_extra_dirs = ${PROJECT_DIR}
lib_ignore = examples
platform = espressif32@6.12.0
framework = arduino
upload_speed = 460800
monitor_speed = 115200
monitor_port = COM11
board_build.partitions = partitions_demo_tts.csv
extra_scripts = post:scripts/upload_voice_data.py
build_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=0
	-DUSE_LOCAL_ESP_TTS=1
	-Ilib/esp_tts_chinese/include
	-Llib/esp_tts_chinese/esp32s3
	-lvoice_set_xiaole
	-lesp_tts_chinese

monitor_filters = 
	default
	esp32_exception_decoder

lib_deps = 
	lewisxhe/SensorLib @ 0.3.1
	lennarthennigs/Button2 @ 2.3.2
	Wire
	SPI
    bblanchon/ArduinoJson@^7.4.2
    earlephilhower/ESP8266Audio@^1.9.9

[env:T5-ePaper-S3]
extends = env
board = T5-ePaper-S3
upload_port = COM11
build_flags = ${env.build_flags}
	-DLILYGO_T5_EPD47_S3

; older ESP32-WROVER-E device. Note: not all examples fully work.
; https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/issues/177#issuecomment-3747498636
[env:T5-ePaper]
extends = env
board = T5-ePaper
[VoiceStory TTS input] text preview end ----------
Local TTS heap check: free_internal=188136 largest_internal=139252
Generating local esp-tts WAV for id 510 using chinese parser -> /voice/510/tts.wav
init voice set:template
Local ESP-TTS voice: sample_rate=16000 data=0x3c1f9e78 sylls=0x3fc992e8 syll_pos=0x3c1d0028 pinyin_idx=0x3c1d1b80
Local ESP-TTS voice initialized from voice_data partition: name=xiaole_20220719 format=amr sample_rate=16000 bit_width=16
ESP Chinese TTS v1.7 (Sep 22 2022 14:35:13, 1)
[VoiceStory TTS] parsing chinese segment bytes=60 preview=在大不里士老城铜铁巷的尽头有一个
[VoiceStory TTS] parsing chinese segment bytes=18 preview=人的打铁铺。
[VoiceStory TTS] parsing chinese segment bytes=54 preview=铺主卡齐姆是一位体壮如牛的波斯铁
[VoiceStory TTS] parsing chinese segment bytes=18 preview=他老年得子，
[VoiceStory TTS] parsing chinese segment bytes=27 preview=儿���贾拉尔才十岁，
[VoiceStory TTS] parsing chinese segment bytes=60 preview=聪明得能从废铁渣里拼出不同动物形
[VoiceStory TTS] parsing chinese segment bytes=6 preview=兽。
[VoiceStory TTS] parsing chinese segment bytes=62 preview=这一年从大不里士东南面来了一个名
[VoiceStory TTS] parsing chinese segment bytes=18 preview=的神秘邪派。
[VoiceStory TTS] parsing chinese segment bytes=36 preview=教首穿着金箔缀成的斗篷，
[VoiceStory TTS] parsing chinese segment bytes=61 preview=声称要在里海边的山腹内浇铸一尊四
[VoiceStory TTS] parsing chinese segment bytes=37 preview=恒不饿像"——用纯金打造，
[VoiceStory TTS] parsing chinese segment bytes=60 preview=信奉者在像前奉献全部私产便永不再
[VoiceStory TTS] parsing chinese segment bytes=60 preview=而他铸造此像最关键的一个工序是必
[VoiceStory TTS] parsing chinese segment bytes=62 preview=从未说过谎话的童男作为灌入金汤的
[VoiceStory TTS] parsing chinese segment bytes=51 preview=即在那孩子胸窝处凿一小铜管通金汁
[VoiceStory TTS] parsing chinese segment bytes=39 preview=然后让金汁冷却后人像合一。
[VoiceStory TTS] parsing chinese segment bytes=36 preview=他们到处搜索���合的童男，
[VoiceStory TTS] parsing chinese segment bytes=60 preview=最终把目光落在了铁匠卡齐姆从来不
[VoiceStory TTS] parsing chinese segment bytes=24 preview=儿子贾拉尔身上。
[VoiceStory TTS] parsing chinese segment bytes=60 preview=一天夜里金面教派人把贾拉尔从铺后
[VoiceStory TTS] parsing chinese segment bytes=3 preview=。
Aborting local TTS WAV generation after chunk write/parse failure
[VoiceStory TTS] local ESP-TTS result storyId=510 ok=0 path=
[VoiceStory TTS] local ESP-TTS generation failed for storyId=510upload_port = /dev/ttyUSB0
build_flags = ${env.build_flags}
	-DLILYGO_T5_EPD47
  -DESP_EXT1_WAKEUP_ANY_LOW=ESP_EXT1_WAKEUP_ALL_LOW
